-- Baseline schema. Collapses the original hand-rolled migrations into a single
-- starting point. Do NOT edit this file once shipped; add a new numbered file
-- (02-*.sql, 03-*.sql, ...) for every future schema change.

CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS storyboards (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    image_model TEXT NOT NULL DEFAULT 'imagen4',
    video_model TEXT NOT NULL DEFAULT 'veo3',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shots (
    id TEXT PRIMARY KEY,
    storyboard_id TEXT NOT NULL REFERENCES storyboards(id) ON DELETE CASCADE,
    "order" INTEGER NOT NULL,
    duration INTEGER NOT NULL DEFAULT 8,
    image_prompt TEXT,
    image_path TEXT,
    end_frame_path TEXT,
    video_prompt TEXT,
    video_path TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_storyboards_project ON storyboards(project_id);
CREATE INDEX IF NOT EXISTS idx_shots_storyboard ON shots(storyboard_id);

CREATE TABLE IF NOT EXISTS timeline_edits (
    id TEXT PRIMARY KEY,
    storyboard_id TEXT NOT NULL REFERENCES storyboards(id) ON DELETE CASCADE,
    shot_id TEXT NOT NULL REFERENCES shots(id) ON DELETE CASCADE,
    trim_in REAL NOT NULL DEFAULT 0,
    trim_out REAL NOT NULL DEFAULT 8,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(storyboard_id, shot_id)
);

CREATE INDEX IF NOT EXISTS idx_timeline_edits_storyboard ON timeline_edits(storyboard_id);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS image_versions (
    id TEXT PRIMARY KEY,
    shot_id TEXT NOT NULL REFERENCES shots(id) ON DELETE CASCADE,
    parent_version_id TEXT REFERENCES image_versions(id) ON DELETE SET NULL,
    version_number INTEGER NOT NULL,
    edit_type TEXT NOT NULL CHECK(edit_type IN ('generation', 'regeneration', 'remix', 'inpaint')),
    image_path TEXT NOT NULL,
    prompt TEXT,
    edit_prompt TEXT,
    mask_path TEXT,
    is_current INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_image_versions_shot ON image_versions(shot_id);
CREATE INDEX IF NOT EXISTS idx_image_versions_parent ON image_versions(parent_version_id);

CREATE TABLE IF NOT EXISTS video_versions (
    id TEXT PRIMARY KEY,
    shot_id TEXT NOT NULL REFERENCES shots(id) ON DELETE CASCADE,
    parent_version_id TEXT REFERENCES video_versions(id) ON DELETE SET NULL,
    version_number INTEGER NOT NULL,
    edit_type TEXT NOT NULL CHECK(edit_type IN ('generation', 'regeneration', 'extend')),
    video_path TEXT NOT NULL,
    prompt TEXT,
    settings_json TEXT,
    model_id TEXT,
    is_current INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_video_versions_shot ON video_versions(shot_id);
CREATE INDEX IF NOT EXISTS idx_video_versions_parent ON video_versions(parent_version_id);

CREATE TABLE IF NOT EXISTS timeline_tracks (
    id TEXT PRIMARY KEY,
    storyboard_id TEXT NOT NULL REFERENCES storyboards(id) ON DELETE CASCADE,
    track_id TEXT NOT NULL,
    name TEXT NOT NULL,
    track_type TEXT NOT NULL CHECK(track_type IN ('video', 'audio')),
    position INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(storyboard_id, track_id)
);
CREATE INDEX IF NOT EXISTS idx_timeline_tracks_storyboard ON timeline_tracks(storyboard_id);

CREATE TABLE IF NOT EXISTS timeline_clips (
    id TEXT PRIMARY KEY,
    storyboard_id TEXT NOT NULL REFERENCES storyboards(id) ON DELETE CASCADE,
    shot_id TEXT NOT NULL REFERENCES shots(id) ON DELETE CASCADE,
    track_id TEXT NOT NULL,
    start_time REAL NOT NULL DEFAULT 0.0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_timeline_clips_storyboard ON timeline_clips(storyboard_id);

CREATE TABLE IF NOT EXISTS bibles (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    is_default INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_bibles_project ON bibles(project_id);

CREATE TABLE IF NOT EXISTS bible_assets (
    id TEXT PRIMARY KEY,
    bible_id TEXT NOT NULL REFERENCES bibles(id) ON DELETE CASCADE,
    asset_type TEXT NOT NULL CHECK(asset_type IN ('character', 'location', 'prop', 'style', 'reference', 'note', 'scene')),
    name TEXT NOT NULL,
    summary TEXT,
    description TEXT,
    tags_json TEXT,
    rules_json TEXT,
    consent_confirmed INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft', 'approved', 'archived')),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_bible_assets_bible ON bible_assets(bible_id);

CREATE TABLE IF NOT EXISTS bible_asset_variants (
    id TEXT PRIMARY KEY,
    asset_id TEXT NOT NULL REFERENCES bible_assets(id) ON DELETE CASCADE,
    parent_variant_id TEXT REFERENCES bible_asset_variants(id) ON DELETE SET NULL,
    name TEXT,
    status TEXT NOT NULL DEFAULT 'candidate' CHECK(status IN ('candidate', 'approved', 'rejected')),
    media_path TEXT,
    prompt TEXT,
    negative_prompt TEXT,
    model_id TEXT,
    source_kind TEXT NOT NULL CHECK(source_kind IN ('uploaded', 'generated', 'edited', 'imported')),
    is_primary INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_bible_asset_variants_asset ON bible_asset_variants(asset_id);

CREATE TRIGGER IF NOT EXISTS trg_projects_create_main_bible
AFTER INSERT ON projects
WHEN NOT EXISTS (SELECT 1 FROM bibles WHERE project_id = NEW.id)
BEGIN
    INSERT INTO bibles (id, project_id, name, is_default)
    VALUES ('bible-' || NEW.id, NEW.id, 'Main Bible', 1);
END;
